### PR TITLE
Allow to deploy NFS clients without an nfs_server host

### PR DESCRIPTION
**Pull request by priteau**
If the host nfs_server is not defined, get nfs_export from variables.

### CODE REVIEW

**Review by brtkwr — CHANGES_REQUESTED** [review]
Would this not work?
`hostvars[nfs_server]['nfs_export'] | default('nfs_export')`

Mark suggests:
`hostvars[nfs_server].get('nfs_export', 'nfs_export')`

**Comment by priteau** [comment]
@brtknr `hostvars[nfs_server]['nfs_export'] | default('nfs_export')` doesn't work, as `default` applies to fetching `['nfs_export']`, not `[nfs_server]`. The error is:

    The task includes an option with an undefined variable. The error was: u\"hostvars['192.168.3.129']\" is undefined

(192.168.3.129 being the value of `nfs_server` in this instance).

Mark's suggestion fails in exactly the same way.

**Comment by oneswig** [comment]
I had the logic the other way round, as in, a local `nfs_export` variable, default to retrieving the value from `host_vars[nfs_server]...`

**Comment by priteau** [comment]
> I had the logic the other way round, as in, a local `nfs_export` variable, default to retrieving the value from `host_vars[nfs_server]...`

If we do this, we would have to remove the default value from `defaults/main.yml`, as it would be used in priority over hostvars.

**Comment by jovial** [comment]
To join in the bike shedding, isn't the standard chaining idiom something like:
`hostvars.get(nfs_server, {}).get('nfs_export', nfs_export)`?

**Comment by brtkwr** [comment]
Bravo @jovial! Although the second `nfs_export` also needs to be in quotes: `hostvars.get(nfs_server, {}).get('nfs_export', 'nfs_export')`

**Comment by priteau** [comment]
> To join in the bike shedding, isn't the standard chaining idiom something like:
> `hostvars.get(nfs_server, {}).get('nfs_export', nfs_export)`?

This would work in Python, but doesn't appear to be supported by Jinja2 / Ansible.

**Comment by priteau** [comment]
> Bravo @jovial! Although the second `nfs_export` also needs to be in quotes: `hostvars.get(nfs_server, {}).get('nfs_export', 'nfs_export')`

I don't understand why would want to quote the second `nfs_export`, since we want the value of the variable, not the string `"nfs_export"`.

**Comment by priteau** [comment]
More reading on the issue:

* https://medium.com/opsops/fighting-with-limitation-of-default-filter-in-jinja2-ansible-a39c47096b9c
* https://github.com/ansible/ansible/issues/30944

**Comment by priteau** [comment]
> I had the logic the other way round, as in, a local `nfs_export` variable, default to retrieving the value from `host_vars[nfs_server]...`

Also you cannot do `{{ nfs_export | default(hostvars[nfs_server]['nfs_export']) }}` because Ansible will try to retrieve the value of `hostvars[nfs_server]['nfs_export']` while interpreting the statement, not just if the `default` filter gets executed.

**Comment by oneswig** [comment]
We are over-thinking this.  I don't think we should be implicitly extracting hostvars.  We have defined a parameter, `nfs_export`,  which is what we should stick to.  The caller can do the fiddly hostvars dereference on module invocation.

**Comment by priteau** [comment]
I don't actually need this change anymore using the new approach of https://github.com/cedadev/jasmin-appliances/pull/16, but we can still make it easier for callers to configure NFS clients with an existing server.

**Review by oneswig — APPROVED** [review]
OK, well I think it's the right thing to remove the implicit dependency on `hostvars['nfs_server']`

**Review by brtkwr — APPROVED** [review]

**Review by brtkwr — APPROVED** [review]

**Pull request merged**
